<?php
	/*  Plugin Name:Video Upload
		Plugin URI:http://www.google.com
		Auther:Ajay Kumar
		Description: We can use this plugin to upload video from user and send it to admin autherization.
	*/
	
	//create the table in database if not exist.
	
	
	function cron_options_install() {

    global $wpdb;
    global $tbl_name;
    $tbl_name = $wpdb->prefix . 'ak_video';

    // create the ECPT metabox database table
    if ($wpdb->get_var("show tables like '$tbl_name'") != $tbl_name) {
        $charset_collate = $wpdb->get_charset_collate();
        $sql = "CREATE TABLE IF NOT EXISTS `$tbl_name` (
                        `ID` int(11) NOT NULL AUTO_INCREMENT,
                        `FILENAME` varchar(225) NOT NULL,
						`TITLE` varchar(225) NOT NULL,
                         PRIMARY KEY (`ID`)
                      ) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;";
        $wpdb->query($sql);
    }

    require_once(ABSPATH . 'wp-admin/includes/upgrade.php');
}


function deleteDirectory($dir) {
    if (!file_exists($dir)) {
        return true;
    }

    if (!is_dir($dir)) {
        return unlink($dir);
    }

    foreach (scandir($dir) as $item) {
        if ($item == '.' || $item == '..') {
            continue;
        }

        if (!deleteDirectory($dir . DIRECTORY_SEPARATOR . $item)) {
            return false;
        }

    }

    return rmdir($dir);
}





function cron_options_uninstall() {
    global $wpdb;
    global $tbl_name;
    $tbl_name = $wpdb->prefix . 'ak_video';
   
    global $wpdb;
    $wpdb->query("DROP TABLE IF EXISTS $tbl_name");
	$dir="../wp-content/uploads";
	deleteDirectory($dir);
  
}

register_activation_hook(__FILE__, 'cron_options_install');
register_deactivation_hook(__FILE__, 'cron_options_uninstall');

	
	

	
	$wp_login_form_options= get_option('loginformsettings');
	//admin Page
	
	function video_upload_page(){
		global $wp_login_form_options;
		
		
	ob_start();?>
	<script type="text/javascript" src="<?php echo plugin_dir_url(__FILE__)."/js/video.js";?>">
</script>
<link href="<?php echo plugin_dir_url(__FILE__)."/css/style.css";?>" rel="stylesheet"/>
	
	
	<div class="main-container">
	
	
	
	<?php

extract($_POST);


$target_dir = "../wp-content/uploads".date("Y/m/");
if(!empty($_FILES['fileToUpload']['name'])):
$target_file = $target_dir . basename($_FILES['fileToUpload']['name']);
endif;
if(!empty($upd)&& !empty($target_file))
{
	$imageFileType = pathinfo($target_file,PATHINFO_EXTENSION);
	
	if($imageFileType != "mp4" && $imageFileType != "avi" && $imageFileType != "mov" && $imageFileType != "3gp" && $imageFileType != "mpeg")
 {
     echo "<h2 style='color:red;text-align:center;'>File Format Not Suppoted!</h2>";
 }
else{
	
	if ( ! function_exists( 'wp_handle_upload' ) ) {
    require_once( ABSPATH . 'wp-admin/includes/image.php' );
	require_once( ABSPATH . 'wp-admin/includes/file.php' );
	require_once( ABSPATH . 'wp-admin/includes/media.php' );
}

$uploadedfile = $_FILES['fileToUpload'];

$upload_overrides = array( 'test_form' => false );

$movefile = wp_handle_upload( $uploadedfile, $upload_overrides );

if ( $movefile && !isset( $movefile['error'] ) ) {
	
	$video_path=$_FILES['fileToUpload']['name'];
	
global $wpdb;

$wpdb->insert( 
	'wp_ak_video', 
	array( 
		 
		'FILENAME' => date("Y/m/").$video_path,
		'TITLE' => $_REQUEST['title']
	), 
	array( 
		'%s' 
	) 
);

	
	
    echo "<h2>File is valid, and was successfully uploaded.\n</h2>";
	
    
} else {
    /**
     * Error generated by _wp_handle_upload()
     * @see _wp_handle_upload() in wp-admin/includes/file.php
     */
    echo $movefile['error'];
}
	
	
}	

}

//display all uploaded video

if(!empty($disp))

{
global $wpdb;
$fivesdrafts = $wpdb->get_results( 
	"
	SELECT FILENAME, TITLE
	FROM wp_ak_video
	"
);
$count=0;
foreach ( $fivesdrafts as $fivesdraft ) 
{
	$count++;
?>
	
<div class="tv-box" id="tv<?php echo  $count;?>">
<p style="text-align:center" ><b>SAMSUNG</b></p>
	<video width="100%" height="auto" border="1" id="player<?php echo  $count;?>">
	
	<source src="../wp-content/uploads/<?php echo $fivesdraft->FILENAME; ?>" type="video/mp4">
	<source src="../wp-content/uploads/<?php echo $fivesdraft->FILENAME; ?>" type="video/ogg" />
	<source src="../wp-content/uploads/<?php echo $fivesdraft->FILENAME; ?>" type="video/avi">
	<source src="../wp-content/uploads/<?php echo $fivesdraft->FILENAME; ?>" type="video/mov" />
	<source src="../wp-content/uploads/<?php echo $fivesdraft->FILENAME; ?>" type="video/webm">
	<source src="../wp-content/uploads/<?php echo $fivesdraft->FILENAME; ?>" type="video/3gp" />
	</video>
	<div class="pull-left">
    <button id="restart<?php echo  $count;?>" onclick="restart(<?php echo  $count;?>);" alt="restart">()</button> 
    <button id="rew" onclick="skip(-10,<?php echo  $count;?>)" alt="Rew">&lt;&lt;</button>
    <button id="play<?php echo  $count;?>" onclick="vidplay(<?php echo  $count;?>)" alt="play">&gt;</button>
    <button id="fastFwd" onclick="skip(10,<?php echo  $count;?>)">&gt;&gt;</button>
	</div>
	<p style="text-align:right;"><b>Video Title :  <?php echo $fivesdraft->TITLE; ?></b></p>
	
	
</div>
	
	
	
<?php }} ?>
<div class="button-style">
	<h1 style="text-align:center">Upload your video here..</h1>
	<form method="post" enctype="multipart/form-data">

<table  cellpadding="10" cellspacing="100" align="center">

	<tr>
		<td>
			<input type="file" name="fileToUpload" class="btn-success btn" style="margin:5px;"/>
		</td>
	</tr>
	<tr>
		<td>
			<input type="text" name="title" class="form-control"  placeholder="Enter the video title"  id="vidTitle"/>
		</td>
	</tr>
	<tr>
		<td>
			<input type="submit" value="Uplaod Video" name="upd" class="btn btn-success" onclick="titlecheck()"/>
			<input type="submit" value="Display Video" name="disp" class="btn btn-success"/>
		</td>
	</tr>

</table>

</form>	
		</div>
	
	
	
	<?php	
	echo ob_get_clean();
	}
	
	
	
	//Login Form
	
	function wp_video_upload_form(){
		
		add_options_page('video upload','Video Upload','manage_options','videoupload','video_upload_page');
		
	}
	add_action('admin_menu','wp_video_upload_form');
	
	
	add_shortcode('videouploadtest', 'video_upload_page');
	
	?>